# -*- coding: utf-8 -*-
"""DS hmk2 pr2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17NXsKDK-6O_HYPuzmj7NCdZyr34gIPpm
"""

!pip install scrapy

import time
import requests
import numpy as np
import pandas as pd
from scrapy.http import TextResponse
import re

def movie_scraper(url,base_url="https://www.imdb.com/chart/moviemeter/"):
    page = requests.get(url)
    response = TextResponse(body=page.text,url=url,encoding="utf-8")
    title = response.css("td.titleColumn >a ::text").extract()
    release_year = response.css("td >span.secondaryInfo::text").extract()
    year = [i.replace("(" , "").replace(")" , "") for i in release_year]
    ratings_table = response.css("td.ratingColumn.imdbRating")
    rating = [i.css('strong::text').extract_first() for i in ratings_table]
    movurl = response.css("td.titleColumn ::attr(href)").extract()
    hyperlink = 'https://www.imdb.com/'
    movie_hyperlink = [hyperlink+i for i in movurl]
    rank_div = response.css("div.velocity")
    rank_ext = [i.css("::text").extract_first() for i in rank_div]
    ranks = [i.replace('\n',"").replace("(no change)","") for i in rank_ext]  
    return pd.DataFrame({"Title":title,  "Year":year, "Ratings":rating, "Movie_Hyperlink": movie_hyperlink , 'Rank':ranks,})

sm =movie_scraper(url = "https://www.imdb.com/chart/moviemeter/")
sm

